### ISSUE TITLE
Error while running the app which uses angular-cordova plugins

### ISSUE THREAD

**Issue by faheemhameed** [arnesson/angular-cordova#10]
Dear there,

Thanks for providing this library for cordova. When I tried to run the angular app I got the following error.

```
ERROR in ./node_modules/angular-cordova/index.ts
Module build failed: Error: /Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/angular-cordova/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/angular-cordova/plugin/camera.ts
Module build failed: Error: /Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/angular-cordova/plugin/camera.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/hameedbs/Projects/accountpilotv2/httpdocs/ngapp/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


```

It is blocking me to proceed... Thanks for your help in advance..

PS: I am using vscode IDE and it showed some lint errors in your ts files.

**Comment by robertarnesson** [comment]
see https://github.com/arnesson/angular-cordova/issues/9

**Comment by faheemhameed** [comment]
Thanks a lot!!! That fixed it.
