### ISSUE TITLE
Error on ng serve

### ISSUE THREAD

**Issue by gschafra** [arnesson/angular-cordova#9]
Got following error, when initiating "ng serve":

```typescript
ERROR in ./node_modules/angular-cordova/index.ts
Module build failed: Error: D:\vlinux\frontend\2017-12-12_dekra_city_app\node_modules\angular-cordova\index.ts is missing f
rom the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly pac
kaged library. Please open an issue in the library repository to alert its author and ask them to package the library using
 the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\vlinux\frontend\2017-12-12_dekra_city_app\node_modules\@ngtools\webpack\sr
c\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\vlinux\frontend\2017-12-12_dekra_city_app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
**Angular-Version/Environment:**
```
Angular CLI: 1.7.4
Node: 6.14.1
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.4
@angular/language-service: 4.4.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
angular-cordova:1.0.0
typescript: 2.4.2
webpack: 3.11.0
```
**tsconfig.json:**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noStrictGenericChecks":  true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by robertarnesson** [comment]
add angular-cordova to tsconfig.json:

"include": [
    "./node_modules/angular-cordova/**/*"
  ]

**Comment by gschafra** [comment]
Works with:
```json
"include": [
        "src/**/*",
        "./node_modules/angular-cordova/**/*"
 ],
```
Thanks a lot!
